name: Essentials
version: '${project.version}'
main: me.evan.essentials.Essentials
commands:
  nick:
    description: Set your nickname to...whatever you want!
  god:
    description: Become invulnerable!
  fly:
    description: Become icarus..just don't go too high up...